---
format:
  html:
    minimal: true
    theme: none
    page-layout: custom
    toc: false
    include-in-header:
      text: |
        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
---

<section id="cv-page-1">

<!-- ===== MAIN CONTENT ===== -->
<div class="main">

<div class="title">
<h1>Danielle Navarro</h1>
<p>Data scientist, technical writer, behavioural scientist, and software developer</p>
</div>

<div class="subsection">
<h2><i class="fa fa-star" aria-hidden="true"></i> Highlights</h2>
<div class="block">
<ul>
  <li>20 years experience in statistics, experimental design and behavioural science</li>
  <li>Expertise in R, Python, SQL, and modern data science workflows</li>
  <li>Skilled technical writer and communicator with a passion for helping others</li>
  <li>Author of 100+ scientific papers as lead author, analyst or research designer</li>
  <li>Author of several books on data visualisation, art, and statistics</li>
  <li>Research leadership roles, editorial experience, and project management</li>
</ul>
</div>
</div>

<div class="subsection">
<h2><i class="fa fa-suitcase" aria-hidden="true"></i> Employment History</h2>

<div class="block">
<h3>Developer Advocate, Voltron Data <span class="date">(2022)</span></h3>
<ul>
  <li>Open source contributions to improve product usability for developers</li>
  <li>Improve user experience for developers in a complex software ecosystem</li>
  <li>Demonstrate larger-than-memory data workflows to R developer comminity</li>
  <li>Work with software engineers and communicated community feedback</li>
  <li>Reduce barriers to adoption for developers using Apache Arrow</li>
  <li>Develop and delivered training material for technical audiences</li>
</ul>
</div>

<div class="block">
<h3>Associate Professor in Quantitative Psychology / Data Science, University of New South Wales <span class="date">(2016–2021)</span></h3>
<ul>
  <li>Data analysis, statistical modelling, and Bayesian methods</li>
  <li>A/B testing and advanced experimental design</li>
  <li>Research software engineering, typically in R and Javascript</li>
  <li>Project management, finances, and team leadership</li>
  <li>Curriculum development and delivery for technical content</li>
  <li>Research grant and report writing, and publishing scientific research</li>
  <li>Leadership roles in the broader scientific community</li>
  <li>Editorial responsibilities at leading scientific journals</li>
</ul>
</div>

<div class="block">
<h3>Earlier Positions <span class="date">(2002–2015)</span></h3>
<ul>
  <li>Associate Professor, University of Adelaide (2012–2015)</li>
  <li>Lecturer/Senior Lecturer, University of Adelaide (2006–2011)</li>
</ul>
</div>
</div>

<div class="subsection">
<h2><i class="fa fa-graduation-cap" aria-hidden="true"></i> Education</h2>
<div class="block">
<ul>
  <li>Ph.D., University of Adelaide (1999–2003). My Ph.D. focused on
    quantitative methods and mathematical modeling in the behavioral sciences.</li>
  <li>Bachelor of Social Science (Honours), University of Adelaide (1994–1998)</li>
</ul>
</div>
</div>

</div>

<!-- ===== SIDEBAR CONTENT ===== -->
<div class="sidebar">

<div class="block">
<h2><i class="fa fa-circle-info" aria-hidden="true"></i> Contact</h2>
<ul>
<li>Email: djnavarro@protonmail.com</li>
<li>GitHub: <a href="https://github.com/djnavarro">github.com/djnavarro</a></li>
<li>Website: <a href="https://djnavarro.net">djnavarro.net</a></li>
</ul>
</div>

<div class="block">
<h2><i class="fa fa-seedling" aria-hidden="true"></i> Mini Portfolio</h2>
<ul>
<li>
  <a href="https://blog.djnavarro.net">blog.djnavarro.net</a><br>
  Data science blog with 108k page views in 2022
</li>
<li>
  <a href="https://learningstatisticswithr.com">learningstatisticswithr.com</a><br>
  Statistics text with 246k page views in 2022
</li>
<li>
  <a href="https://arrow-user2022.netlify.app">arrow-user2022.netlify.app</a><br>
  Short course on big data workflows in R with Apache Arrow
</li>
</ul>
</div>

<div class="block">
<h2><i class="fa fa-code" aria-hidden="true"></i> R, Python, SQL</h2>
<p>
I'm a skilled R data analyst and package developer. I'm comfortable in Python and
SQL, familiar with C++, and use Shiny, Quarto, R markdown, and Jupyter regularly.
</p>
</div>

<div class="block">
<h2><i class="fa fa-chart-pie" aria-hidden="true"></i> Data analysis, modelling</h2>
<p>
I'm skilled at experimental design, data cleaning and visualisation. I'm strong in statistical 
modelling, particularly Bayesian approaches. In addition to standard tools like R, SPSS, 
and Qualtrics, I've used Stan, JAGS, and machine learning methods when relevant.
</p>
</div>

<div class="block">
<h2><i class="fa fa-code-compare" aria-hidden="true"></i> Git, Docker, CI/CD</h2>
<p>
I habitually use git, GitHub, and CI/CD workflows. I'm comfortable with Docker
and cloud services such as AWS and Google Cloud, and have Kubernetes experience.
</p>
</div>

<div class="block">
<h2><i class="fa fa-globe" aria-hidden="true"></i> HTML, CSS, JS</h2>
<p>
I write HTML directly or from templates using generators like Hugo and Jekyll. I'm
just as happy writing my own CSS and JS as using libraries like p5.js, observable.js, 
jspsych, and paged.js.
</p>
</div>

</div>

</section>

<style>
@import url('https://fonts.googleapis.com/css2?family=Belleza&display=swap');

:root {
    --page-width: 210mm;
    --page-margin: 12mm;
    --sidebar-width: 65mm;
    --sidebar-border: 1px solid #ccc;
    --sidebar-border-radius: 10px;
    --sidebar-horizontal-padding: 4mm;
    --sidebar-vertical-padding: 10mm;
    --sidebar-background: whitesmoke;
    --content-width: calc(var(--page-width) - (var(--page-margin) * 2));
    --main-width: calc(var(--content-width) - var(--sidebar-width));
    --main-left-padding: 0;
    --main-right-padding: 8mm;
    --paper-colour: white;
    --paper-shadow-colour: #bfbfbf;
    --text-colour: #444;
    --text-font-size: 10pt;
    --title-font-size: 22pt;
}

@page {
    size: A4 portrait;
    margin: 12mm;

    @bottom-right {
        content: "Résumé: Danielle Navarro.  Updated: March 2023";
        padding: 2mm 4mm;
        width: 70mm;
        height: 10mm;
        font-size: 8pt;
    }
}

@page part1 {
    /* rules for part1 */
}

@page part2 {
    /* rules for part2 */
}

#cv-page-1 {
    page: cv-page-1;
}

#cv-page-2 {
    page: cv-page-2;
}

/* style and interface */

body {
    background-color: var(--paper-colour);
    font-size: var(--text-font-size);
    font-weight: 300;
    color: var(--text-colour);
    font-family: "Belleza", "Open Sans", sans-serif;
    hyphens: auto;
    line-height: 16px;
}

section {
    break-before: page;
}

h1 {
    font-size: var(--title-font-size);
    margin-top: 0;
}

h2 {
    font-size: 16pt;
    margin-top: 0;
    margin-bottom: 5px;
}

.sidebar h2 {
    font-size: 12pt;
}

h3 {
    font-size: 12pt;
    margin: 0;
}

.date {
    font-size: 10pt;
    font-weight: 300;
}

ul {
    padding-left: 0;
    margin-left: 16pt;
}

li {
    margin-left: -4.25pt;
}

.main {
    width: var(--main-width);
    padding-left: var(--main-left-padding);
    padding-right: var(--main-right-padding);
    padding-top: 0;
    padding-bottom: 0;
    float: left;
}

.subsection {
    padding-top: 20px;
    padding-bottom: 0;
}

.block {
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 0;
    padding-right: 0;
    line-height: 1.2;
}


.title {
    position: relative;
    left: 0;
    line-height: 1.2;
    padding-bottom: 12px;
}

.title h1 {
    font-size: var(--title-font-size);
    font-weight: 300;
    padding-bottom: 0px;
    margin-bottom: 0px;
}

.title p {
    padding-top: 0;
}

.sidebar {
    width: var(--sidebar-width);
    padding-left: var(--sidebar-horizontal-padding);
    padding-right: var(--sidebar-horizontal-padding);
    padding-top: var(--sidebar-vertical-padding);
    padding-bottom: var(--sidebar-vertical-padding);
    float: right;
    position: absolute;
    right: 0;
    border: var(--sidebar-border);
    border-radius: var(--sidebar-border-radius);
    background-color: var(--sidebar-background);
}

@media screen,
pagedjs-ignore {

    .pagedjs_page {
        background-color: var(--paper-colour);
        box-shadow: 0 0 0 1px var(--paper-shadow-colour);
        margin: 1mm;
    }

    .pagedjs_pages {
        display: flex;
        max-width: var(--pagedjs-width); /* for two pages: calc(var(--pagedjs-width) * 2 + 5mm); */ 
        flex: 0;
        flex-wrap: wrap;
        margin: 0 auto;
    }

}
</style>
